packages:
  - name: ingestion
    functions:
      - name: sync
        main: handler.py
        runtime: python:3.11
        environment:
          DATABASE_URL: ${DATABASE_URL}
          MEILI_HOST: ${MEILI_HOST}
          MEILI_MASTER_KEY: ${MEILI_MASTER_KEY}
          NOTION_TOKEN: ${NOTION_TOKEN}
          NOTION_INDEX_PAGE_ID: ${NOTION_INDEX_PAGE_ID}
          EMBEDDINGS_PROVIDER: ${EMBEDDINGS_PROVIDER}
          OPENAI_API_KEY: ${OPENAI_API_KEY}
          REVALIDATE_TOKEN: ${REVALIDATE_TOKEN}
          WEB_BASE_URL: ${WEB_BASE_URL}
        triggers:
          - name: scheduled
            type: scheduler
            schedule: "*/10 * * * *"  # Every 10 minutes
