-- Migration: Add AI rendering column to articles table
-- Safe to run on production - adds nullable column with no breaking changes

-- Add the AI rendered HTML column
ALTER TABLE articles 
ADD COLUMN ai_rendered_html TEXT;

-- Add a comment for documentation
COMMENT ON COLUMN articles.ai_rendered_html IS 'AI-optimized HTML content generated by GPT-4o for enhanced formatting and structure';

-- Optional: Create an index if you plan to query based on AI content existence
-- CREATE INDEX idx_articles_ai_rendered ON articles(ai_rendered_html) WHERE ai_rendered_html IS NOT NULL;

-- Verify the column was added successfully
SELECT column_name, data_type, is_nullable 
FROM information_schema.columns 
WHERE table_name = 'articles' 
AND column_name = 'ai_rendered_html';
