name: customer-help-center
region: sfo3

services:
  - name: web
    image:
      registry_type: DOCR
      registry: workco
      repository: customer-help-web
      tag: latest
    http_port: 3000
    instance_count: 1
    instance_size_slug: basic-xs
    envs:
      - key: NODE_ENV
        type: SECRET
      - key: NEXT_PUBLIC_API_URL
        type: SECRET
      - key: BACKEND_URL
        type: SECRET
      - key: OPENAI_API_KEY
        type: SECRET
      - key: REVALIDATE_TOKEN
        type: SECRET
    routes:
      - path: /

  - name: api
    image:
      registry_type: DOCR
      registry: workco
      repository: customer-help-api
      tag: latest
    http_port: 8080
    instance_count: 1
    instance_size_slug: basic-xs
    envs:
      - key: DATABASE_URL
        value: ${customer-help-db.DATABASE_URL}
      - key: MEILI_HOST
        type: SECRET
      - key: MEILI_MASTER_KEY
        type: SECRET
      - key: NOTION_TOKEN
        type: SECRET
      - key: NOTION_INDEX_PAGE_ID
        type: SECRET
      - key: EMBEDDINGS_PROVIDER
        type: SECRET
      - key: OPENAI_API_KEY
        type: SECRET
      - key: REVALIDATE_TOKEN
        type: SECRET
      - key: WEB_BASE_URL
        type: SECRET
      - key: SPACES_KEY
        type: SECRET
      - key: SPACES_SECRET
        type: SECRET
      - key: SPACES_BUCKET
        type: SECRET
      - key: SPACES_REGION
        type: SECRET
      - key: SPACES_CDN_ENDPOINT
        type: SECRET
    routes:
      - path: /backend

databases:
  - cluster_name: customer-help-db
    db_name: defaultdb
    db_user: doadmin
    engine: PG
    name: customer-help-db
    production: true
    version: "17"