#!/bin/bash

echo "🚀 DigitalOcean Database Setup and Ingestion"
echo "============================================"
echo ""
echo "📋 Step 1: Get your database connection string"
echo "   1. Go to: https://cloud.digitalocean.com/databases" 
echo "   2. Click on 'customer-help-db'"
echo "   3. Click 'Connection Pools' tab (or use Connection Details)"
echo "   4. Copy the connection string (postgresql://...)"
echo ""
echo "📋 Step 2: Run the ingestion"
echo ""
echo "Option A - Quick run (one time):"
echo "DO_DATABASE_URL='postgresql://doadmin:password@host:port/defaultdb?sslmode=require' python scripts/run-ingestion-do.py"
echo ""
echo "Option B - Save to .env file (recommended):"
echo "1. Add to apps/api/.env:"
echo "   DO_DATABASE_URL=postgresql://doadmin:..."
echo "2. Then run:"
echo "   python scripts/run-ingestion-do.py"
echo ""
echo "📋 Step 3: Create database schema"
echo "First, let's create the schema in your DO database..."
echo ""
echo "Run this command with your connection string:"
echo "psql 'YOUR_CONNECTION_STRING' < apps/api/db/schema.sql"
echo ""
echo "Or use the helper command:"
echo "python scripts/setup-do-schema.py"
