#!/bin/bash

echo "🔧 Setting up SSH tunnel to DigitalOcean Meilisearch"
echo "=================================================="
echo ""
echo "This allows you to access the private Meilisearch from your local machine"
echo ""
echo "📋 Steps:"
echo "1. Go to your DigitalOcean droplet that hosts Meilisearch"
echo "2. Get the droplet's public IP"
echo "3. Run this command:"
echo ""
echo "ssh -L 7701:10.124.0.39:7700 root@YOUR_DROPLET_PUBLIC_IP"
echo ""
echo "This forwards:"
echo "  localhost:7701 → 10.124.0.39:7700 (through the droplet)"
echo ""
echo "Then update the ingestion script to use:"
echo "  MEILI_HOST=http://localhost:7701"
echo ""
echo "💡 Don't have a droplet with access? Create a small temporary one in the same VPC!"
